[book]
authors = ["Eduardo Antuña Díez"]
language = "en"
multilingual = false
src = "."
title = "ZisK Documentation"

[output.html.playground]
runnable = false

[output.html]
additional-css = ["static/mermaid.css"]

[build]
build-dir = "target/book"




